### ISSUE TITLE
exception happen

### ISSUE THREAD

**Issue by dotkt** [cwoodall/cpp-serde-gen#4]
i love your idea very much. thank you it's very nice tool.
i trigger "cog example-01.cpp.cog > 1.cpp" in python2 in anaconda
but get exception here:
Could not serialize {}
this is the 1.cpp file content:
![图片](https://user-images.githubusercontent.com/49758966/84221417-c5361c80-ab07-11ea-96fa-e5723f478838.png)

what is the problem can you help me solve it?

**Comment by cwoodall** [comment]
What exactly is the error?

**Comment by cwoodall** [comment]
@dotkt I only see the 1.cpp file. What exception do you get?

What are you trying to do with the resulting cpp file?

**Comment by dotkt** [comment]
Traceback (most recent call last):                                                                                  
  File "example-01.cpp.cog", line 52, in <module>                                                                   
    tu = get_clang_TranslationUnit(cog.inFile)                                                                      
  File "c:\programdata\anaconda2\lib\site-packages\cpp_serde_gen\__init__.py", line 28, in get_clang_TranslationUnit
    syspath = ccsyspath.system_include_paths('clang++')                                                             
  File "c:\programdata\anaconda2\lib\site-packages\ccsyspath\paths.py", line 25, in system_include_paths            
    lines = compiler_preprocessor_verbose(compiler, extraflags)                                                     
  File "c:\programdata\anaconda2\lib\site-packages\ccsyspath\paths.py", line 14, in compiler_preprocessor_verbose   
    p = subprocess.Popen(cmd, stdin=devnull, stdout=PIPE, stderr=PIPE)                                              
  File "c:\programdata\anaconda2\lib\subprocess.py", line 394, in __init__                                          
    errread, errwrite)                                                                                              
  File "c:\programdata\anaconda2\lib\subprocess.py", line 644, in _execute_child                                    
    startupinfo)                                                                                                    
WindowsError: [Error 2]

**Comment by cwoodall** [comment]
Looks to me like you might not have clang installed!

**Comment by dotkt** [comment]
emm ..yeah .sorry i 'll figure it out how to install the clang env in my win10  thank you very much
